apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  labels:
    app: keydb
  name: keydb-0
  namespace: d003
spec:
  ports:
  - name: keydb
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    statefulset.kubernetes.io/pod-name: keydb-0
  type: LoadBalancer
  loadBalancerIP: 10.201.197.9
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  labels:
    app: keydb
  name: keydb-1
  namespace: d003
spec:
  ports:
  - name: keydb
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    statefulset.kubernetes.io/pod-name: keydb-1
  type: LoadBalancer
  loadBalancerIP: 10.201.197.208
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  labels:
    app: keydb
  name: keydb-2
  namespace: d003
spec:
  ports:
  - name: keydb
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    statefulset.kubernetes.io/pod-name: keydb-2
  type: LoadBalancer
  loadBalancerIP: 10.201.197.217