## A persistent volume for MongoDB replica data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-eu-pvc
  namespace: d003
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard

## Explicitly listing MongoDB endpoint from NLAM0 k8s cluster
## to provide replica names resolution within the replica set
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongo-rs-mongodb-replicaset
  namespace: d003
subsets:
- addresses:
  - hostname: mongo-rs-mongodb-replicaset-0
    ip: 10.202.133.101
  - hostname: mongo-rs-mongodb-replicaset-1
    ip: 10.202.133.102
  - hostname: mongo-rs-mongodb-replicaset-2
    ip: 10.202.133.103
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP

## Stub service object that would include the endpoints above
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-rs-mongodb-replicaset
  namespace: d003
spec:
  clusterIP: None
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

## Exposing the MongoDB replica to the internal network
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  labels:
    app: mongodb-replicaset
  name: mongo-rs-mongodb
  namespace: d003
spec:
  loadBalancerIP: 10.201.197.50
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb-replicaset
  type: LoadBalancer

## MongoDB replica deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: mongodb-replicaset
  name: mongo-eu
  namespace: d003
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-replicaset
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb-replicaset
    spec:
      containers:
      - command:
        - mongod
        - --replSet
        - rs0
        - --bind_ip
        - 0.0.0.0
        image: mongo:4.4
        imagePullPolicy: IfNotPresent
        name: mongo-eu
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongo-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-eu-pvc
