apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  # The interval at which to reconcile the Helm release
  interval: 10m
  releaseName: redis
  targetNamespace: d003
  chart:
    spec:
      # The path of the chart relative to the repository root
      chart: redis
      version: 16.5.2
      # The reference to the GitRepository
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    nodes: 1
    auth:
      enabled: true
      existingSecret: redis-password-secret
      existingSecretPasswordKey: password
    sentinel:
      enabled: true
      livenessProbe:
        enabled: true
        initialDelaySeconds: 120
      service:
        type: LoadBalancer
    metrics:
      enabled: true
---
apiVersion: v1
data:
  password: aWZqd3JpMmdzZGY5ZmRzYWwxOUAl
kind: Secret
metadata:
  name: redis-password-secret
  namespace: d003
